"""GPS telemetry visualization package."""

from gps_telemetry_visualizer.core import (
    CanvasConfig,
    ElementBounds,
    ElementLayout,
    FrameVisualState,
    OverlayLayout,
    RenderConfig,
    TelemetryData,
    VALID_SPEEDOMETER_STYLES,
    compute_element_bounds,
    compute_frame_states,
    compute_layout_bounds,
    convert_speed,
    default_overlay_layout,
    format_distance,
    format_speed_unit,
    frame_state_at,
    layout_warnings,
    overlay_layout_from_dict,
    overlay_layout_to_dict,
    parse_gps,
    prepare_telemetry,
    preview_to_output_coordinates,
    render_animation,
    render_preview_frames,
    render_static_preview,
    resize_layout_element_from_corner,
    scale_overlay_layout,
)

__all__ = [
    "CanvasConfig",
    "ElementBounds",
    "ElementLayout",
    "FrameVisualState",
    "OverlayLayout",
    "RenderConfig",
    "TelemetryData",
    "VALID_SPEEDOMETER_STYLES",
    "compute_element_bounds",
    "compute_frame_states",
    "compute_layout_bounds",
    "convert_speed",
    "default_overlay_layout",
    "format_distance",
    "format_speed_unit",
    "frame_state_at",
    "layout_warnings",
    "overlay_layout_from_dict",
    "overlay_layout_to_dict",
    "parse_gps",
    "prepare_telemetry",
    "preview_to_output_coordinates",
    "render_animation",
    "render_preview_frames",
    "render_static_preview",
    "resize_layout_element_from_corner",
    "scale_overlay_layout",
]

__version__ = "0.1.0"
